#!/usr/bin/env bash

CLI=/home/dxta/cli
if [ -z "$PS1" ]; then
  echo -e "\033[0;31mYou should source this, not run it, for example: source ./install\033[m"
else
  link () {
    if [ -e $1 ]; then
      if [ -e "$2" ]; then
        rm "$2"
      fi

      ln -s "$1" "$2"
    fi
  }

  # source $HOME/cli/shell/init.sh

  #echo "source $CLI/shell/init.sh" >> ~/.bashrc
  #echo "source $CLI/shell/init.sh" >> ~/.zshrc
  CLI=$HOME/cli

  # vim
  link $CLI/vim/vimrc $HOME/.vimrc
  link $CLI/vim $HOME/.vim
  echo "set t_vb=" >> ~/.gvimrc

  # emacs
  link $CLI/emacs $HOME/.emacs.d

  # git
  link $CLI/git/gitconfig $HOME/.gitconfig
  link $CLI/git/gitignore $HOME/.gitignore

  # ruby
  #link $CLI/ruby/gemrc $HOME/.gemrc
  #link $CLI/ruby/irbrc $HOME/.irbrc
  #link $CLI/ruby/pryrc $HOME/.pryrc

  # misc.
  link $CLI/tmux.conf $HOME/.tmux.conf
  link $CLI/ctags $HOME/.ctags

  # if [ "$OS" = "darwin" ]; then
    # cat $CLI/Custom.css > "$HOME/Library/Application Support/Google/Chrome/Default/User StyleSheets/Custom.css"
  # fi

  # if [ "$OS" = "linux" ]; then
  link $CLI/awesome $HOME/.config/awesome
  link $CLI/x/xinitrc $HOME/.xinitrc
  link $CLI/x/xresources $HOME/.xresources
  link $CLI/x/xmodmap $HOME/.xmodmap
  link $CLI/x/terminalrc $HOME/.config/xfce4/terminal/terminalrc
    # cat $CLI/Custom.css > "$HOME/.config/chromium/Default/User StyleSheets/Custom.css"
  # fi
fi
