#!/bin/bash
HISTORY=$HOME/.config/nitrogen
item="`sed '$!d' $HISTORY/history.txt`"
rm -f $item
previous="`sed '$!d' $HISTORY/history.txt`"
sed '$d' < $HISTORY/history.txt > $HISTORY/temp.txt; mv $HISTORY/temp.txt $HISTORY/history.txt
previous="`sed '$!d' $HISTORY/history.txt`"
nextw
