#! /bin/bash
CONFIG=$HOME/git/dotfiles/.config/nitrogen
RANGE=( `wc -l $CONFIG/customlib.txt | cut -f 1 -d " "` )
let "number = $RANDOM"
let LASTNUM="`cat $CONFIG/.last` + $number"
let "number = $LASTNUM % $RANGE"
echo $number > $CONFIG/.last
argtmp="$number"
argtmp+="p"
echo $argtmp
PIC="`sed -n "$argtmp" $CONFIG/customlib.txt`"
echo $PIC
#nitrogen --set-zoom --save ""$PIC""
gsettings set org.gnome.desktop.background picture-uri "file://$PIC"
gsettings set com.canonical.unity-greeter background "file://$PIC"
let "curr_no=`grep -c "." $CONFIG/history.txt`"
if [ $curr_no -ge 10 ]; then
  sed '1d' < $CONFIG/history.txt > $CONFIG/temp.txt; mv $CONFIG/temp.txt $CONFIG/history.txt
  echo $PIC >> $CONFIG/history.txt
else
  echo $PIC >> $CONFIG/history.txt
fi

