#! /bin/bash
HISTORY=$HOME/.config/nitrogen

previous="`sed '$!d' $HISTORY/history.txt`"
sed '$d' < $HISTORY/history.txt > $HISTORY/temp.txt; mv $HISTORY/temp.txt $HISTORY/history.txt
previous="`sed '$!d' $HISTORY/history.txt`"
echo $previous
nitrogen --set-zoom --save "$previous"
gsettings set org.gnome.desktop.background picture-uri "file://$previous"
gsettings set com.canonical.unity-greeter background "file://$previous"
