" Vim configuration
" Tung Dao <me@tungdao.com>


" Bundle
set nocompatible
runtime bundle/vim-unbundle/plugin/unbundle.vim
let $PATH=$HOME.'/.rbenv/shims/:'.$HOME.'/local/bin/:'.$PATH

" Config
let mapleader=","
filetype plugin on
runtime! config/*.vim
