#!/bin/sh

source /etc/X11/xinit/xinitrc.d/30-dbus

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

xfsettingsd
xfce4-power-manager
# xfce4-volumed
xrdb -merge $HOME/.xresources
xmodmap $HOME/.xmodmap
xflux -l 21.0 -g 105.8 &
xinput set-prop 13 293 -107 -107

compton -e 1 &
xautolock -time 15 -locker $HOME/cli/bin/i3lock-locker &
TERM=xterm-256color emacs --daemon &
clipit &
dropboxd &
# $HOME/local/bin/rescuetime &

wmname LG3D
exec dbus-launch awesome --no-argb
