#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

xrandr --output LVDS --mode 1366x768
xrandr --output VGA-0 --mode 1280x1024
xrandr --output VGA-0 --right-of LVDS

xfce4-power-manager
xrdb -merge $HOME/.xresources
$HOME/cli/bin/natural-scroll
xmodmap $HOME/.xmodmap
xflux -l 21.0 -g 105.8 &

mpd
mpdas &
xautolock -time 15 -locker $HOME/cli/bin/i3lock-locker &
clipit &
dropboxd &

exec awesome --no-argb
