#! /bin/bash
WALLPAPERS="/media/Data/SkyDrive/Pictures/Desktop-Background"
ALIST=( `ls -w1 $WALLPAPERS` )
RANGE=${#ALIST[@]}
HISTORY=$HOME/.config/nitrogen
let "number = $RANDOM"
let LASTNUM="`cat $WALLPAPERS/.last` + $number"
let "number = $LASTNUM % $RANGE"
echo $number > $WALLPAPERS/.last
nitrogen --set-zoom --save $WALLPAPERS/${ALIST[$number]}
gsettings set org.gnome.desktop.background picture-uri $WALLPAPERS/${ALIST[$number]}
gsettings set com.canonical.unity-greeter background $WALLPAPERs/${ALIST[$number]}
let "curr_no=`grep -c "." $HISTORY/history.txt`"
if [ $curr_no -ge 5 ]; then
  sed '1d' < $HISTORY/history.txt > $HISTORY/temp.txt; mv $HISTORY/temp.txt $HISTORY/history.txt
  echo $WALLPAPERS/${ALIST[$number]} >> $HISTORY/history.txt
else
  echo $WALLPAPERS/${ALIST[$number]} >> $HISTORY/history.txt
fi

