;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        indent-for-tab-command
        org-self-insert-command
        sgml-slash
        sp--self-insert-command
        sp-forward-slurp-sexp
        td/join-next-line
        td/kill-region-or-word
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        undo-tree-visualizer-quit
        ))
