;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        evil-find-char-to
        kill-region-or-word
        org-force-self-insert
        org-self-insert-command
        toggle-input-method
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        forward-sentence
        org-shiftcontroldown
        ))
