(source gnu)
(source melpa)

;;;; Auto complete
(depends-on ac-c-headers)
(depends-on ac-nrepl)
(depends-on auto-complete)
(depends-on go-autocomplete)

(depends-on smex)
(depends-on ido-ubiquitous)
(depends-on ido-vertical-mode)

;;;; Editing
(depends-on ace-jump-mode)

(depends-on undo-tree)

(depends-on evil)
(depends-on evil-visualstar)
(depends-on surround)

(depends-on expand-region)
(depends-on multiple-cursors)
(depends-on yasnippet)

;;;; Project
(depends-on projectile)

(depends-on ag)
(depends-on wgrep-ag)

(depends-on magit)
(depends-on diff-hl)
(depends-on ibuffer-vc)

;;;; UI
(depends-on popwin)
(depends-on diminish)
(depends-on color-theme-approximate)
(depends-on number-font-lock-mode)
(depends-on rainbow-delimiters)
(depends-on rainbow-mode)

(depends-on sublime-themes)
(depends-on solarized-theme)
(depends-on twilight-theme)

;;;; Programming
(depends-on flycheck)
(depends-on emmet-mode)
(depends-on restclient)

(depends-on mmm-mode)

(depends-on go-eldoc)
(depends-on go-mode)

(depends-on clojure-mode)
(depends-on cider)

(depends-on javadoc-lookup)
(depends-on groovy-mode)

(depends-on lua-mode)

(depends-on php-mode)
(depends-on inf-php)

(depends-on robe)
(depends-on inf-ruby)

(depends-on tern)
(depends-on tern-auto-complete)
(depends-on tss)
(depends-on nodejs-repl)
(depends-on json-mode)
(depends-on coffee-mode)

(depends-on markdown-mode)

(depends-on rust-mode)

(depends-on scala-mode2)

(depends-on scss-mode)

(depends-on yaml-mode)

;;;; Utils
(depends-on dash)
(depends-on s)
(depends-on exec-path-from-shell)
(depends-on simpleclip)
